### ISSUE TITLE
pluginSystray: Sorry, the systray icon is only available on Windows so far

### ISSUE THREAD

**Issue by unsystemizer** [namecoin/nmcontrol#119]
```
$ sudo python2 nmcontrol.py --daemon=0 --debug=1 start
2016-05-27 11:21:15,283 - __main__ - INFO - #######################################################
2016-05-27 11:21:15,286 - __main__ - DEBUG - DEBUG MODE 1 (set from console)
2016-05-27 11:21:15,318 - __main__ - DEBUG - launching service serviceDNS
2016-05-27 11:21:16,068 - __main__ - DEBUG - launching plugin pluginData
2016-05-27 11:21:16,086 - __main__ - DEBUG - launching plugin pluginDns
2016-05-27 11:21:16,094 - __main__ - DEBUG - launching plugin pluginHttp
2016-05-27 11:21:16,328 - __main__ - DEBUG - launching plugin pluginNamespaceDomain
2016-05-27 11:21:16,334 - __main__ - DEBUG - launching plugin pluginRpc
2016-05-27 11:21:16,341 - __main__ - DEBUG - launching plugin pluginSystray
2016-05-27 11:21:16,349 - plugin - DEBUG - Plugin domain parent starting
2016-05-27 11:21:16,352 - plugin - DEBUG - Plugin http parent starting
2016-05-27 11:21:16,355 - pluginHttp - DEBUG - Starting HTTP server...
2016-05-27 11:21:16,356 - plugin - DEBUG - Plugin dns parent starting
2016-05-27 11:21:16,358 - plugin - DEBUG - Plugin data parent starting
2016-05-27 11:21:16,360 - plugin - DEBUG - Plugin dns parent starting
2016-05-27 11:21:16,361 - pluginNamespaceDomain - DEBUG - Set up DNS handlers, len = 1
Bottle v0.12.9 server starting up (using WSGIRefServer())...
Listening on http://127.0.0.2:8080/
Hit Ctrl-C to quit.

2016-05-27 11:21:16,361 - plugin - DEBUG - Plugin dns parent start
2016-05-27 11:21:16,383 - serviceDNS - DEBUG - Service dns started
2016-05-27 11:21:16,390 - __main__ - INFO - Plugins started : domain, http, dns, systray
2016-05-27 11:21:16,392 - plugin - DEBUG - Plugin systray parent starting
2016-05-27 11:21:16,394 - plugin - DEBUG - Plugin main parent starting
2016-05-27 11:21:16,399 - plugin - DEBUG - Plugin rpc parent starting
2016-05-27 11:21:16,402 - pluginRpc - INFO - nmc-manager: unable to listen on port
2016-05-27 11:21:16,398 - pluginSystray - DEBUG - Systray.py: Plugin systray parent start
Traceback (most recent call last):
  File "nmcontrol.py", line 169, in <module>
    main()
  File "nmcontrol.py", line 160, in main
    app['plugins']['main'].start2()
  File "/nmcontrol-master/lib/plugin.py", line 68, in start2
    return self.pStart()
  File "/nmcontrol-master/plugin/pluginMain.py", line 18, in pStart
    app['plugins']['rpc'].start2()
  File "/nmcontrol-master/lib/plugin.py", line 68, in start2
    return self.pStart()
  File "/nmcontrol-master/plugin/pluginRpc.py", line 40, in pStart
    log.debug("pStart", excinfo=1)
  File "/usr/lib/python2.7/logging/__init__.py", line 1155, in debug
    self._log(DEBUG, msg, args, **kwargs)
  File "/nmcontrol-master/lib/mylogging.py", line 40, in _log
    Logger._log(self, level, msg, args, **kwargs)
TypeError: _log() got an unexpected keyword argument 'excinfo'
2016-05-27 11:21:16,409 - pluginSystray - INFO - pluginSystray: Sorry, the systray icon is only available on Windows so far.
```
- Ubuntu 16.04 on armhf
##

**Comment by JeremyRand** [comment]
-----BEGIN PGP SIGNED MESSAGE-----
Hash: SHA256

Did the `excinfo` argument to log.debug() get removed in a recent
version of Python or something?

This doesn't appear to have anything to do with the systray plugin,
it's an issue relating to logging as far as I can tell.  Might be as
easy to fix as removing the `excinfo` argument from line 40 of
`pluginRpc.py`.  If that fixes it for you, please let us know and/or
send in a pull request.
-----BEGIN PGP SIGNATURE-----
Version: GnuPG v2

iQIcBAEBCAAGBQJXR8P7AAoJEAHN/EbZ1y060VIQAMubSVg4EESaqI0/7Z/L3IqM
JqUGkHzoip9IqdhvMH+pHxOnDexF5phuFvxnUDm4zuhl3byv8oN/uWkcJBygFQGd
e52UjfkXcZFK4K3uYGgMh3uzG6ljPPcZT2weqLKExu3JSi1VTYoohutJ1Cg0VUcp
loKiiRFdsY9JLPULRNgIBtIuTKYllk2okJw/G64nK81RKNl829xovuLFTtBnB9ua
GWuXg5iKQ6jNRhd4jFwnsEUWcHAJf5EYS4XpJ53l+vNBnzN6tR3CNbjn/67ZOU2q
bMdCzzlR0GnqbnA4UBVGfhUr9Qcxukr9XCNWqmCGfykdBsA1qIu4/7i4Bc+WZY//
+s9iS/A1KVsCbzVnz+mORsZ/R77T2gA8gcjPpuBQNcZpa+MR0nTwXC7zYOWytJ02
ivcpTxtrA2b2bIUQK2QDRLFVpveS2P1aEjiA1GLKbAmAROo/acVAlNdDoglW/2kC
GInyt+dZlCnnbLJm2/tW9tLKs1HdOGrk+91P/yN1TXlXjg+CgMYTMlqos9muw1CJ
kg0IR0F8kAigFanx7bPr78o+eTy1mPm/oTkiil7EfoGIKX1cEOuuyEmB9W8VImDt
IXe38Q3GvFovdMu2/sVY8oeFnLiVcCyeesSrUnGEy5fKi8bhgehCmEYO2FueJllX
nk6ufqw0iXj5sRUSQkNC
=OTnS
-----END PGP SIGNATURE-----

**Comment by yield65** [comment]
Hello,
Just ran into the same problem, removing "excinfo" didn't help. It just hang for about 5 seconds and then just stop.

**Comment by JeremyRand** [comment]
-----BEGIN PGP SIGNED MESSAGE-----
Hash: SHA512

Yield:

> Hello, Just ran into the same problem, removing "excinfo" didn't
> help. It just hang for about 5 seconds and then just stop.

If you're unaware, NMControl is planned to be replaced with ncdns in
the foreseeable future, so it's unlikely that much effort will be put
into a codebase that's deprecated.
-----BEGIN PGP SIGNATURE-----

iQIcBAEBCgAGBQJYJAg3AAoJELPy0WV4bWVwSosP/2Ci2jBfmb90ZZuSFyS7Hc0j
DWMxyM3bIjRDdNfZjm+0Dl5rF5aKFPf8FYM/+DgZtl2djAEA5GOqJiu8MoCCv50X
dB6Paa3VAZch8Ke0ec0BRhuXQ/1F1VIWr6LNYbhd5L6XX+ST4pEnMSKrIjI56c2i
ShW5p8EiSVuwwEz/yvhC2I08GIsZkjgAMyYzh2QzMP4bTdIZXBVa7kXv5IiuHcc6
a6f4IKmxPOoO1ozeFxYoriFvR1z3kp1eke8hdr/wDfmk8HGM8SpgqOuMac7tevX4
PB4RX6MWZcd7hvnSTbNZFWMbeRd+kP4aokCTt/xw1UIh96j1BMuBA3Z+ivVyRSwL
Dn4qcnMKnPeeVg2ZRb6W7HkdxxSdHdD7YxdLlLWdbA4u7plUuoHwaMi7PSv0HWMs
OZKlFPlhmrDWz0eWBd9TyGH3ZDi5YqZk6QsmyplbYCMZMIabljCpad1XzccEJj9q
L3U0VqXXTWPlKYQcjdmX85b7DUAqflmz95Zn5t2UlFEeajnH2yQ82fCas5CFeI3a
8Zd85OVItcDB1nXLFle6Kfbu0tq1AccBvs+Q2tUKLhTwqdkLpkA0reiySqxOxmQe
WxwyU6KCjXOC7l8aflFlYDORqXxPBzLp9JMxdPUwcKwROrOuLiwOcsYD3WrNoMpt
Lgs8WHUX1PA8WABiY1l0
=JNSr
-----END PGP SIGNATURE-----

**Comment by yield65** [comment]
Ok, thanks.

**Comment by nagromc** [comment]
@JeremyRand Are you talking about [hlandau/ncdns](https://github.com/hlandau/ncdns)?

**Comment by JeremyRand** [comment]
-----BEGIN PGP SIGNED MESSAGE-----
Hash: SHA512

Morgan Courbet:

> @JeremyRand Are you talking about
> [hlandau/ncdns](https://github.com/hlandau/ncdns)?

Yes.  It will probably move to the namecoin user on GitHub at some point
.

-----BEGIN PGP SIGNATURE-----

iQIcBAEBCgAGBQJYJCyaAAoJELPy0WV4bWVw+5AQALhiyD+gqllBvln9kEZtuHXy
26IX3AwC9StXASZWWA3pHm1Leabmr5MxhqfCbcMJLMPLyNEqc8S7jEUC0re5lDyf
CkkCEpKCQC3ZbgxE1MewkW9+bKsEJtVmQ9EirOgLrNNcKF/kDkaStcyUfvU5F8ec
70ARwYbScbsTfZYIv+QxP02rCYjcEjR51HQ3/A8lzvXrHuCJnNz1EAVmnAYl8wsC
iEiiv2uS1dWTRQvkuFKPd6i1+HNJHjalYAKAFDvhvwwyasoJCwXNoOFf2w47S034
6FLaVpog1/D0Iaowe4PTAOUN8H32XY/umgIO2hE9S27DXjXi+7jOV88grbENuFy9
lPbIKjW6r6TnJ/CmcKFI28s2FRZJdRi16sIILxe4SeeibX6pEUoUf8ezgnDp2x0H
HZBfUjSseSsEmSEndFo/ezG0fvPxKb7iEZSaDZ5AdtCTu3ctPkFLdADx6Yj8Zj2W
PRoQIUU4VakHQbctzVWgoUVVtfDkDHsRZaeUX5Wn6KWJqkZqTyNYePkdlvyTqch5
StUkgPSfY3ByvyEUcOyiqZ7r7P7MrV0aw5rKTXIjcbsMJcS8Vr+Q5Z171dNmGGNq
DN1Cl3sYxdGUY+y1LQgA4+NJ6FA3ISCp6m2RSc6caZGmlbnHca/KCIlXINhd/rQV
Zq5YkuxPzuwLTYvQG5AA
=yQYF
-----END PGP SIGNATURE-----
